import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ToggleDataButton from './components/ToggleDataButton'
import CreateUserForm from './components/CreateUserForm'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <p>Teste</p>
          <p>Clique no botão abaixo para realizar uma requisição dos dados da Database.</p>
          <ToggleDataButton/>
        </div>
        <div>
          < CreateUserForm />
        </div>

      </main>
    </>
  )
}
